// register
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

// login
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// fetch user profile
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'
export const FETCH_USER_RESET = 'FETCH_USER_RESET'

// fetch single user
export const FETCH_SINGLE_USER_REQUEST = 'FETCH_SINGLE_USER_REQUEST'
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_FAIL = 'FETCH_SINGLE_USER_FAIL'

// update user
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

// delete user
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

// fetch all users
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

// update user 
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

// Fetch all category
export const FETCH_ALL_CATEGORY_STARTED = "FETCH_ALL_CATEGORY_STARTED";
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS";
export const FETCH_ALL_CATEGORY_FAILURE = "FETCH_ALL_CATEGORY_FAILURE"

// delete category
export const DELETE_CATEGORY_STARTED = "DELETE_CATEGORY_STARTED";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE"

//update category
export const UPDATE_CATEGORY_STARTED = "UPDATE_CATEGORY_STARTED"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE "

// Add category
export const ADD_CATEGORY_STARTED = "ADD_CATEGORY_STARTED";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

// Fetch all products
export const FETCH_ALL_PRODUCT_STARTED = "FETCH_ALL_PRODUCT_STARTED";
export const FETCH_ALL_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCT_SUCCESS";
export const FETCH_ALL_PRODUCT_FAILURE = "FETCH_ALL_PRODUCT_FAILURE"

// Fetch top products
export const FETCH_TOP_PRODUCT_STARTED = "FETCH_TOP_PRODUCT_STARTED";
export const FETCH_TOP_PRODUCT_SUCCESS = "FETCH_TOP_PRODUCT_SUCCESS";
export const FETCH_TOP_PRODUCT_FAILURE = "FETCH_TOP_PRODUCT_FAILURE"

// Fetch single product
export const FETCH_SINGLE_PRODUCT_STARTED = "FETCH_SINGLE_PRODUCT_STARTED";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAILURE = "FETCH_SINGLE_PRODUCT_FAILURE"

//delete product
export const DELETE_PRODUCT_STARTED = "DELETE_PRODUCT_STARTED"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE"

//update product
export const UPDATE_PRODUCT_STARTED = "UPDATE_PRODUCT_STARTED"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE "

// Add product
export const ADD_PRODUCT_STARTED = "ADD_PRODUCT_STARTED";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

// Add reviews
export const ADD_REVIEWS_STARTED = "ADD_REVIEWS_STARTED";
export const ADD_REVIEWS_SUCCESS = "ADD_REVIEWS_SUCCESS";
export const ADD_REVIEWS_FAILURE = "ADD_REVIEWS_FAILURE";

// Fetch all orders
export const FETCH_ALL_ORDERS_STARTED = "FETCH_ALL_ORDERS_STARTED";
export const FETCH_ALL_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";
export const FETCH_ALL_ORDERS_FAILURE = "FETCH_ALL_ORDERS_FAILURE"

// Fetch my orders
export const FETCH_MY_ORDERS_STARTED = "FETCH_MY_ORDERS_STARTED";
export const FETCH_MY_ORDERS_SUCCESS = "FETCH_MY_ORDERS_SUCCESS";
export const FETCH_MY_ORDERS_FAILURE = "FETCH_MY_ORDERS_FAILURE"

// Add order
export const ADD_ORDER_STARTED = "ADD_ORDER_STARTED";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

//delete order 
export const DELETE_ORDER_STARTED = "DELETE_ORDER_STARTED"
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"

// Fetch single order
export const FETCH_SINGLE_ORDER_STARTED = "FETCH_SINGLE_ORDER_STARTED";
export const FETCH_SINGLE_ORDER_SUCCESS = "FETCH_SINGLE_ORDER_SUCCESS";
export const FETCH_SINGLE_ORDER_FAILURE = "FETCH_SINGLE_ORDER_FAILURE"

//update order to delivered
export const UPDATE_ORDER_DELIVERED_STARTED = "UPDATE_ORDER_DELIVERED_STARTED"
export const UPDATE_ORDER_DELIVERED_SUCCESS = "UPDATE_ORDER_DELIVERED_SUCCESS"
export const UPDATE_ORDER_DELIVERED_FAILURE = "UPDATE_ORDER_DELIVERED_FAILURE "

//pay order 
export const PAY_ORDER_STARTED = "PAY_ORDER_STARTED"
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS"
export const PAY_ORDER_FAILURE = "PAY_ORDER_FAILURE"

// cart
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const SHIPPING_ADDRESS = "SHIPPING_ADDRESS"
export const PAYMENT_METHOD = "PAYMENT_METHOD"
